name: twitterclon
description: "A new Flutter project."

# Previene publicar accidentalmente el paquete en pub.dev
publish_to: 'none'  # Eliminar esta línea si deseas publicar en pub.dev

# Definición de la versión de la aplicación
version: 1.0.0+1

# Especifica la versión del SDK de Dart que se requiere
environment:
  sdk: ^3.5.1

# Dependencias necesarias para la aplicación
dependencies:
  flutter:
    sdk: flutter  # Flutter SDK
  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.0
  provider: ^6.1.2
  firebase_auth: ^5.3.3 # Autenticación Firebase

dev_dependencies:
  flutter_test:
    sdk: flutter  # Dependencias para pruebas de Flutter
  flutter_lints: ^5.0.0  # Paquete de recomendaciones de lints

flutter:
  uses-material-design: true  # Usar el diseño Material de Flutter

  # Sección de assets (si tienes imágenes o archivos estáticos)
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # Sección de fuentes (si tienes fuentes personalizadas)
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
